---
# tasks file for docker


#TODO add supporting platforms debian - ubuntu

- name: "Install dependency"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present


- name: Install Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
  - docker-ce
  - docker-ce-cli
  - containerd.io


- name: Chech that Docker started
  service:
    name: docker
    state: started
    enabled: yes


- name: Install Docker python package for Ansible
  pip:
    name: "{{item}}"
  loop:
  - docker
  - docker-compose
